# Generated by Django 2.1.2 on 2018-10-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=50)),
                ('times_number', models.IntegerField(default=0)),
                ('sets_number', models.IntegerField(default=0)),
                ('times_type', models.IntegerField(default=50)),
                ('week', models.IntegerField(default=0)),
            ],
        ),
    ]
