# Generated by Django 2.1.2 on 2018-10-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20181028_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmenu',
            name='times_type',
            field=models.CharField(max_length=10),
        ),
    ]
